### ISSUE TITLE
Is it possible to trim the extra libs?

### ISSUE THREAD

**Issue by schwiz** [AuthorizeNet/sdk-android#2]
My concern is over the logging and junit libs included in this project. Considering the low method count limit on Android it would be preferable to not include the libs especially on production builds. Is it possible to build jars not requiring these extra libs?

**Comment by ncpga** [comment]
You can select/remove the jars during the build process. The Android build will also smartly remove extra binaries. Resolution is also posted on:
https://github.com/AuthorizeNet/sdk-android/issues/6
