### ISSUE TITLE
E00003: Invalid character in the given encoding

### ISSUE THREAD

**Issue by rpt** [AuthorizeNet/sdk-android#5]
I get this error when sending '®' in the OrderItem's name or description. I cannot find a way to specify the encoding of the XML via the SDK. The generated XML always starts with `<?xml version="1.0"?>...` without any encoding (when I print it with `request.toAuthNetPOSTString()`).

Is there a way to set the encoding?
Is this a bug on the server side or in the SDK?

//cc @rhldr

**Comment by ncpga** [comment]
The default encoding is UTF-8. You need to do XML escape to that special char '®'. Here is the reference: http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references

**Comment by rpt** [comment]
@ncpga I don't understand why you closed the issue - it's still a bug. It doesn't makes sense to me to escape utf-8 characters in an utf-8 encoded xml, but if you say that's the solution then the SDK should be fixed.

**Comment by rpt** [comment]
Hello? Is anyone working on a fix for that? The API is still not accepting UTF-8 encoded XMLs.

**Comment by halfnibble** [comment]
I'm having a similar issue with the Web API. Did you find a resolution?

**Comment by rpt** [comment]
I just didn't use UTF-8 characters. Don't count on those guys to fix anything, you have to find a workaround yourself.
