### ISSUE TITLE
Error with Android SDk

### ISSUE THREAD

**Issue by humayunajmal** [AuthorizeNet/sdk-android#6]
I am trying this example 
http://developer.authorize.net/integration/fifteenminutes/android/

but I m getting Lint error 

The import net.authorize.android cannot be resolved

Also I can't find this class in any JAR file and in source of SDK.

**Comment by ncpga** [comment]
Hi, we will look into it tomorrow and get back to you. Sorry for the inconvenience.

**Comment by ncpga** [comment]
Hi, here are the build steps that I use. I just adjust some environment settings in the IDEs and no need to move files around to get the builds successful. Please see if it is helpful:

To build the Android SDK(with IntelliJ(v14.0.2)):
1.	 “Open” the source code directly.
2.	In File->Project Structure, specify the “Project SDK” to the proper JDK version, 
3.	Add dependency jars(in \lib directory) to Libraries 
4.	Specify Modules Sources, exclude irrelevant directories
5.	Specify output paths, check “Exclude output paths” option 
6.	Add Artifacts, choose “From modules with dependencies”, check “Build on Make” option
7.	Check Dependencies
8.	Build the project, copy the ANET SDK jar to the Sample App lib directory

To build the Sample App(with Android studio(v1.0.1)):
1.	 “Open” the source code directly.
2.	In File->Project Structure, specify the “Project SDK” to the proper Android SDK version, 
3.	Add Android Facets, reset Structure files and directories as appropriate
4.	Add android-support-v4.jar and ANET SDK jar(in \lib directory) to Libraries 
5.	Specify Modules Sources, exclude irrelevant directories
6.	Specify output paths, check “Exclude output paths” option 
7.	Check Dependencies
8.	Build the project

**Comment by pkhutal** [comment]
Hi,
How can i integrate with Android using eclipse.please provide me link where can i get this or step by step guide.
