### ISSUE TITLE
android package non-existent in src

### ISSUE THREAD

**Issue by bmurmistro** [AuthorizeNet/sdk-android#7]
Following http://developer.authorize.net/integration/fifteenminutes/android

Clearly these files are missing in this project:

import net.authorize.android.AuthNet;
import net.authorize.android.AuthNetActivityBase;
import net.authorize.android.SimpleActivity;
import net.authorize.android.button.AuthNetButton;

Where do I find the jar for these?

**Comment by bmurmistro** [comment]
@ncpga Thanks the response. I'm able to build it just fine. However, the android package is still missing. The package simply does not even exist in the source: https://github.com/AuthorizeNet/sdk-android/tree/master/src/net/authorize

Unless the build process generates these files, I don't see where these files come from. Any ideas?

**Comment by ncpga** [comment]
We fixed the integration manual. Now it uses the latest SDK and sample in GitHub. Thanks for pointing it out.

**Comment by bmurmistro** [comment]
No problem. Thanks!
