### ISSUE TITLE
Currency code is missing

### ISSUE THREAD

**Issue by rpt** [AuthorizeNet/sdk-android#8]
Continuing on #1, the `currencyCode` field is missing both in [API Reference Guide](http://developer.authorize.net/api/reference/) and this SDK. Anyone looking into this?

**Comment by Idorobots** [comment]
:+1:

**Comment by ncpga** [comment]
The currency is set in merchant account, and that is where the transaction will pick up the currency code. Setting currency code in AIM will not set or change the currency code for the transaction.
